import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full ${font.className}`}>
      <body className="flex flex-col min-h-full">
        {/* Header */}
        <header className="container mx-auto p-4">
          <h1 className="text-4xl">How to Start a Startup</h1>
        </header>

        {/* Main content */}
        <main className="flex-1 container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
